---
kind: pipeline
type: docker
name: windows-1809

# Currently have to define "depth" as otherwise clone fails at
# https://github.com/drone/drone-git/blob/39d233b3d9eccc68e66508a06a725a2567f33143/windows/clone-tag.ps1#L12
clone:
  depth: 20

platform:
  os: windows
  arch: amd64
  version: 1809

steps:
  - name: docker-build
    image: plugins/docker
    settings:
      dry_run: true
      build_args:
        - SERVER_VERSION=ltsc2019
        - ARCH=amd64
        - VERSION=${DRONE_TAG}
      context: package/windows
      custom_dns: 1.1.1.1
      dockerfile: package/windows/Dockerfile
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
      repo: rancher/windows_exporter-package
      tag: ${DRONE_COMMIT/+/-}-windows-1809
    volumes:
      - name: docker_pipe
        path: \\\\.\\pipe\\docker_engine
    when:
      event:
        - pull_request
  - name: docker-publish
    image: plugins/docker
    settings:
      build_args:
        - SERVER_VERSION=ltsc2019
        - ARCH=amd64
        - VERSION=${DRONE_TAG}
      context: package/windows
      custom_dns: 1.1.1.1
      dockerfile: package/windows/Dockerfile
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
      repo: rancher/windows_exporter-package
      tag: ${DRONE_TAG}-windows-1809
    volumes:
      - name: docker_pipe
        path: \\\\.\\pipe\\docker_engine
    when:
      event:
        - tag
      ref:
        - refs/heads/master
        - refs/tags/*

volumes:
  - name: docker_pipe
    host:
      path: \\\\.\\pipe\\docker_engine

trigger:
  event:
    exclude:
      - promote

---
kind: pipeline
type: docker
name: windows-2022

platform:
  os: windows
  arch: amd64
  version: 2022

# Currently have to define "depth" as otherwise clone fails at
# https://github.com/drone/drone-git/blob/39d233b3d9eccc68e66508a06a725a2567f33143/windows/clone-tag.ps1#L12
clone:
  depth: 20

steps:
  - name: docker-build
    image: plugins/docker:windows-ltsc2022-amd64
    settings:
      dry_run: true
      build_args:
        - SERVER_VERSION=ltsc2022
        - ARCH=amd64
        - VERSION=${DRONE_TAG}
      context: package/windows
      custom_dns: 1.1.1.1
      dockerfile: package/windows/Dockerfile
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
      repo: rancher/windows_exporter-package
      tag: ${DRONE_COMMIT/+/-}-windows-ltsc2022
    volumes:
      - name: docker_pipe
        path: \\\\.\\pipe\\docker_engine
    when:
      event:
        - pull_request
  - name: docker-publish
    image: plugins/docker:windows-ltsc2022-amd64
    settings:
      build_args:
        - SERVER_VERSION=ltsc2022
        - ARCH=amd64
        - VERSION=${DRONE_TAG}
      context: package/windows
      custom_dns: 1.1.1.1
      dockerfile: package/windows/Dockerfile
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
      repo: rancher/windows_exporter-package
      tag: ${DRONE_TAG}-windows-ltsc2022
    volumes:
      - name: docker_pipe
        path: \\\\.\\pipe\\docker_engine
    when:
      event:
        - tag
      ref:
        - refs/heads/master
        - refs/tags/*

volumes:
  - name: docker_pipe
    host:
      path: \\\\.\\pipe\\docker_engine

trigger:
  event:
    exclude:
      - promote

---
kind: pipeline
type: docker
name: manifest

platform:
  os: linux
  arch: amd64

steps:
  - name: push-manifest
    image: plugins/manifest
    settings:
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
      spec: manifest.tmpl
    when:
      event:
        - tag

trigger:
  event:
    exclude:
    - promote

depends_on:
- windows-1809
- windows-2022
